# Generated by Django 2.2.14 on 2023-03-19 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userReg', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='client',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='user',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='clients',
        ),
        migrations.DeleteModel(
            name='UserActivity',
        ),
    ]
